## ░▀▀█░█▀▀░█░█░█▀▄░█▀▀
## ░▄▀░░▀▀█░█▀█░█▀▄░█░░
## ░▀▀▀░▀▀▀░▀░▀░▀░▀░▀▀▀
##
## rxyhn's Z-Shell configuration
## https://github.com/rxyhn

#while read file
#do 
#  source "$ZDOTDIR/$file.zsh"
#done <<-EOF
#theme
#env
#aliases
#utility
#options
#plugins
#keybinds
#prompt
#EOF
  export PATH="/home/olione/.local/share/fnm:$PATH"
  eval "`fnm env`"
for conf in "$HOME/.zsh/"*.zsh; do
  source "${conf}"
done
unset conf
# vim:ft=zsh:nowrap

